---

- name: Test distribution
  assert:
    that: >
      ansible_os_family == "RedHat" or
      ansible_os_family == "Debian"
  become: yes

- name: Create udev rules file
  template:
    src: rules.j2
    dest: /etc/udev/rules.d/70-persistent-net.rules
  register: udev_rename_netiface_config_changed
  when: udev_rename_netiface_enabled == true
  tags:
    - udev_rename_netiface_config
  become: yes

- include_tasks: tasks/interfaces.yml

- name: Copy interfaces template over
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: "yes"
  become_method: sudo

